[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.testnet]
exchainge_program = "2yvGQ26fz2mvPnxDa2wcTf5Y88hr9sTSJpiZdFqMyQ4L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "~/.config/solana/exchainge-shdw-keypair.json"

